### ISSUE TITLE
failure with Chef 12.0.0

### ISSUE THREAD

**Issue by petere** [opscode-cookbooks/rsync#13]
Running `kitchen test` fails with:

```
[2014-11-25T19:51:11+00:00] ERROR: rsync_serve[tmp] (fake::simple line 3) had an error: NoMethodError: undefined method `global_modules' for Chef::Resource::Template
       [2014-11-25T19:51:11+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> Converge failed on instance <simple-ubuntu-1204>
```

(The failure is not specific to Ubuntu. It also fails on CentOS.)

After trying out different Chef versions by changing `require_chef_omnibus` in `.kitchen.yml`, it appears that this was broken between Chef 11.16.4 and 12.0.0.

Making `global_modules` and `rsync_modules` public instead of protected appears to fix it, but I don't know whether that is a proper fix.

**Comment by ramereth** [comment]
Confirmed this works. Please merge soon!

**Comment by mhenrixon** [comment]
Come on please!

**Comment by rdoorn** [comment]
Guys, can you please update the version numer, and make the version that includes this fix a release in the supermarket? 
Right now, berks keeps using the old version that doesn't include this fix!

Thanks

**Comment by armiller** [comment]
:+1: Please merge soon!

**Comment by mursprung** [comment]
+1 for this
